// web/src/App.vue
<!-- App.vue -->
<template>
    <DebugWrapper v-if="APP_SETTINGS.DebugWrapper">
          <DebugPanel v-if="APP_SETTINGS.DebugWrapper"/>
      <Root />
    </DebugWrapper>
    <Root v-else />
</template>

<script setup>
import DebugPanel from './debug/DebugPanel.vue'
import { APP_SETTINGS } from './config/appSettings'
import DebugWrapper from './debug/DebugWrapper.vue'
import Root from './scenes/Root.vue'
</script>

// web-react/src/App.tsx
import { APP_SETTINGS } from '@config/appSettings.ts';
import DebugWrapper from '@debug/DebugWrapper.tsx';
import DebugPanel from '@debug/DebugPanel.tsx';
import Root from './app/Root.tsx';
import '@styles/main.css'

export default function App() {
  if (APP_SETTINGS.DebugWrapper) {
    return (
      <DebugWrapper>
        <DebugPanel />
        <Root />
      </DebugWrapper>
    )
  }
  return <Root />;
};
