// web/src/interaction/z.primitives/Carousel.vue
<template>
  <div
    ref="carouselEl" 
    :class="['carousel-default', $attrs.class]"
    :style="carouselStyle" 
    :data-id="id" 
    :data-axis="axis"
    :data-lock-prev-at="lockPrevAt"
    :data-lock-next-at="lockNextAt"
    :data-type="'carousel'" 
    :data-react-swipe-commit="reactSwipeCommit ? true : null">

    <!-- Keyed v-for: Vue matches by sceneIndex so components are
         reused (not unmounted/remounted) when the lane index changes,
         preserving internal animations and component state. -->
    <div
      v-for="entry in styledScenes"
      :key="entry.sceneIndex"
      class="scene-default"
      :style="entry.style"
      @transitionend="onTransitionEnd">
      <component :is="entry.component" />
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watchEffect } from 'vue'
import { state } from '../state/stateManager'
import { useLaneSizing } from './composables/useLaneSizing'
import { usePointerForwarding } from '../bridge/bridge'
import { useCarouselMotion } from './composables/useLaneMotion'
import { useCarouselScenes } from './composables/useLaneScenes'

defineOptions({ inheritAttrs: false })

const emit = defineEmits(['swipeCommit'])

const props = defineProps({
  id: { type: String, required: true },
  axis: { type: String, default: 'horizontal' },
  scenes: { type: Array, default: () => [] },
  reactSwipeCommit: { type: Boolean, default: false },
  lockPrevAt: { type: Number, required: false },
  lockNextAt: { type: Number, required: false }
})

const carouselEl = ref(null)

const horizontal = computed(() => props.axis === 'horizontal')
const laneState = state.get('carousel', props.id)

watchEffect(() => {
  state.setCount('carousel', props.id, props.scenes.length)
})

const { laneSize } = useLaneSizing({
  elRef: carouselEl,
  axisRef: computed(() => props.axis),
  type: 'carousel',
  id: computed(() => props.id)
})

usePointerForwarding({
  elRef: carouselEl,
  onReaction(e) {
    if (!props.reactSwipeCommit) return
    if (e.detail?.event !== 'swipeCommit') return
    emit('swipeCommit', e.detail)
  }
})

const { visibleScenes } = useCarouselScenes({
  scenes: computed(() => props.scenes),
  laneState
})

const { styleForRole, carouselStyle, onTransitionEnd } = useCarouselMotion({
  laneState,
  laneSize,
  horizontal,
  id: props.id
})

// Attach computed style to each visible scene entry by role
const roleStyles = {
  prev: styleForRole('prev'),
  current: styleForRole('current'),
  next: styleForRole('next')
}
const styledScenes = computed(() =>
  visibleScenes.value.map(entry => ({
    ...entry,
    style: roleStyles[entry.role].value
  }))
)
</script>

<style scoped>
.carousel-default {
  touch-action: none;
  transform: translateZ(0);
  -webkit-transform: translateZ(0);
}

.scene-default {
  user-select: none;
  contain: layout style paint;
}
</style>

// web-react/src/components/primitives/carousel/Carousel.tsx
import { useRef, useEffect, useMemo } from "react"
import { carouselStateFn } from "@interaction/state/carouselState.ts"
import { usePointerForwarding } from "@interaction/bridge/bridge.ts"
import { useCarouselMotion } from "./hooks/useCarouselMotion.ts"
import { useCarouselSizing } from "./hooks/useCarouselSizing.ts"
import { useAugmentedScenes } from "./hooks/useAugmentedScenes.ts"
import type { SceneRole } from "./hooks/useCarouselScenes.ts"
import { subscribe } from "@interaction/state/zustandHook.ts"

interface CarouselProps {
  id: string
  axis: 'horizontal' | 'vertical'
  scenes: React.ComponentType[]
  className?: string
  lockPrevAt?: number
  lockNextAt?: number
  reactSwipeCommit?: boolean
  interactive?: boolean
  onSwipeCommit?: (detail: unknown) => void
}

interface Slot {
  sceneIdx: number
  role: SceneRole
}

export default function Carousel({
  id,
  axis,
  scenes,
  className,
  lockPrevAt,
  lockNextAt,
  onSwipeCommit,
  interactive = true
}: CarouselProps) {

subscribe.useFull('carousel', id)

  useEffect(() => {
    if (interactive)
      carouselStateFn.setCount(id, scenes.length)
  }, [id, scenes.length, interactive])


  const carouselRef = useRef<HTMLDivElement>(null)
  const lane = carouselStateFn.ensure(id)

  const augmentedScenes = useAugmentedScenes(scenes, interactive, lane?.count)
  const index = lane?.index ?? 0
  const total = augmentedScenes.length

  const laneSize = useCarouselSizing({
    elRef: carouselRef,
    axis,
    id
  })

  usePointerForwarding({
    elRef: carouselRef,
    disabled: !interactive,
    onReaction: (reaction) => {
      if (reaction.type === 'swipeCommit' && onSwipeCommit) {
        onSwipeCommit(reaction.detail)
      }
    }
  })

  // ── Stable slot management ──────────────────────────────────

  const prevIndexRef = useRef(index)

  const slots: Slot[] = useMemo(() => {
    const prevIdx = (index - 1 + total) % total
    const nextIdx = (index + 1) % total
    return [
      { sceneIdx: prevIdx, role: "prev" as const },
      { sceneIdx: index, role: "current" as const },
      { sceneIdx: nextIdx, role: "next" as const },
    ]
  }, [index, total])

  // prevIndexRef.current = index
  useEffect(() => { prevIndexRef.current = index }, [index])

  useEffect(() => {
    carouselStateFn.setCurrentScenes(id, slots.map(s => s.sceneIdx))
  }, [index, id, total, slots])

  const Scene0 = augmentedScenes[slots[0].sceneIdx]
  const Scene1 = augmentedScenes[slots[1].sceneIdx]
  const Scene2 = augmentedScenes[slots[2].sceneIdx]

  const {
    carouselStyle,
    styleForRole,
    onTransitionEnd
  } = useCarouselMotion({
    laneState: lane,
    laneSize,
    horizontal: axis === "horizontal",
    id
  })

  return (
    <div
      data-type="carousel"
      ref={carouselRef}
      style={{ ...carouselStyle, pointerEvents: interactive ? "auto" : "none" }}
      data-id={id}
      data-axis={axis}
      data-lock-prev-at={lockPrevAt ?? ''}
      data-lock-next-at={lockNextAt ?? ''}
      className={className}
    >
      <div
        className="scene-default"
        style={styleForRole(slots[0].role)}
        data-role={slots[0].role}
        onTransitionEnd={onTransitionEnd}
      >
        <Scene0 />
      </div>
      <div
        className="scene-default"
        style={styleForRole(slots[1].role)}
        data-role={slots[1].role}
        onTransitionEnd={onTransitionEnd}
      >
        <Scene1 />
      </div>
      <div
        className="scene-default"
        style={styleForRole(slots[2].role)}
        data-role={slots[2].role}
        onTransitionEnd={onTransitionEnd}
      >
        <Scene2 />
      </div>
    </div>
  )
}
