// web/src/interaction/z.primitives/Carousel.vue
<template>
  <div
    ref="carouselEl" 
    :class="['carousel-default', $attrs.class]"
    :style="carouselStyle" 
    :data-id="id" 
    :data-axis="axis"
    :data-lock-prev-at="lockPrevAt"
    :data-lock-next-at="lockNextAt"
    :data-type="'carousel'" 
    :data-react-swipe-commit="reactSwipeCommit ? true : null">

    <!-- Keyed v-for: Vue matches by sceneIndex so components are
         reused (not unmounted/remounted) when the lane index changes,
         preserving internal animations and component state. -->
    <div
      v-for="entry in styledScenes"
      :key="entry.sceneIndex"
      class="scene-default"
      :style="entry.style"
      @transitionend="onTransitionEnd">
      <component :is="entry.component" />
    </div>
  </div>
</template>

<script setup>
import { ref, computed, watchEffect } from 'vue'
import { state } from '../state/stateManager'
import { useLaneSizing } from './composables/useLaneSizing'
import { usePointerForwarding } from '../bridge/bridge'
import { useCarouselMotion } from './composables/useLaneMotion'
import { useCarouselScenes } from './composables/useLaneScenes'

defineOptions({ inheritAttrs: false })

const emit = defineEmits(['swipeCommit'])

const props = defineProps({
  id: { type: String, required: true },
  axis: { type: String, default: 'horizontal' },
  scenes: { type: Array, default: () => [] },
  reactSwipeCommit: { type: Boolean, default: false },
  lockPrevAt: { type: Number, required: false },
  lockNextAt: { type: Number, required: false }
})

const carouselEl = ref(null)

const horizontal = computed(() => props.axis === 'horizontal')
const laneState = state.get('carousel', props.id)

watchEffect(() => {
  state.setCount('carousel', props.id, props.scenes.length)
})

const { laneSize } = useLaneSizing({
  elRef: carouselEl,
  axisRef: computed(() => props.axis),
  type: 'carousel',
  id: computed(() => props.id)
})

usePointerForwarding({
  elRef: carouselEl,
  onReaction(e) {
    if (!props.reactSwipeCommit) return
    if (e.detail?.event !== 'swipeCommit') return
    emit('swipeCommit', e.detail)
  }
})

const { visibleScenes } = useCarouselScenes({
  scenes: computed(() => props.scenes),
  laneState
})

const { styleForRole, carouselStyle, onTransitionEnd } = useCarouselMotion({
  laneState,
  laneSize,
  horizontal,
  id: props.id
})

// Attach computed style to each visible scene entry by role
const roleStyles = {
  prev: styleForRole('prev'),
  current: styleForRole('current'),
  next: styleForRole('next')
}
const styledScenes = computed(() =>
  visibleScenes.value.map(entry => ({
    ...entry,
    style: roleStyles[entry.role].value
  }))
)
</script>

<style scoped>
.carousel-default {
  touch-action: none;
  transform: translateZ(0);
  -webkit-transform: translateZ(0);
}

.scene-default {
  user-select: none;
  contain: layout style paint;
}
</style>

// web-react/src/components/Carousel.tsx
import { useRef, useEffect } from "react"
import { state } from "@interaction/state/stateManager"
import { usePointerForwarding } from "@interaction/bridge/bridge.ts"
import { useCarouselState } from "@interaction/state/carouselState.ts"
import { useCarouselMotion } from "@hooks/carousel/useCarouselMotion.ts"
import { useCarouselSizing } from "@hooks/carousel/useCarouselSizing.ts"
import { useCarouselScenes } from "@hooks/carousel/useCarouselScenes.ts"

interface CarouselProps {
  id: string
  axis: 'horizontal' | 'vertical'
  scenes: React.ComponentType[]
  className?: string // for any additional classes
  lockPrevAt?: number
  lockNextAt?: number
  reactSwipeCommit?: boolean
  onSwipeCommit?: (detail: unknown) => void
}

export default function Carousel({
  id,
  axis,
  scenes,
  className,
  lockPrevAt,
  lockNextAt,
  onSwipeCommit,
}: CarouselProps) {

  useEffect(() => {
    state.ensure('carousel', id)
  }, [id])

  useEffect(() => {
    state.setCount('carousel', id, scenes.length)
  }, [id, scenes.length])

  const carouselRef = useRef<HTMLDivElement>(null)

  const lane = useCarouselState.useStore(s => s.lanes[id])

  const laneSize = useCarouselSizing({
    elRef: carouselRef,
    axis,
    id
  })

  usePointerForwarding({
    elRef: carouselRef,
    onReaction: (reaction) => {
      if (reaction.type === 'swipeCommit' && onSwipeCommit) {
        onSwipeCommit(reaction.detail)
      }
    }
  })

  const { visibleScenes } = useCarouselScenes({
    scenes,
    laneState: lane ?? { index: 0 },
  })

  const {
    carouselStyle,
    styleForRole,
    onTransitionEnd
  } = useCarouselMotion({
    laneState: lane ?? { offset: 0, dragging: false, settling: false },
    laneSize,
    horizontal: axis === "horizontal",
    id
  })

  return (
    <div
      data-type="carousel"
      ref={carouselRef}
      style={carouselStyle}
      data-id={id}
      data-axis={axis}
      data-lock-prev-at={lockPrevAt ?? ''}
      data-lock-next-at={lockNextAt ?? ''}
      className={className}
      onTransitionEnd={onTransitionEnd}
    >
      {visibleScenes.map(({ sceneIndex, component: SceneComponent, role }) => (
        <div
          key={sceneIndex}
          className="scene-default"
          style={styleForRole(role)}
          data-role={role}
        >
          <SceneComponent />
        </div>
      ))}
    </div>
  )
}
