// web/src/interaction/z.primitives/Button.vue
<template>
  <div
    ref="buttonEl" 
    class="non-interactive-default">
    <div ref="buttonItem" 
    class="interactive-default"
      v-bind="$attrs"
      :data-id="id"
      :data-press="press ? true : null"
      :data-action="action || null"
      :data-react-press="reactPress ? true : null"
      :data-react-press-release="reactPressRelease ? true : null"
      :data-react-press-cancel="reactPressCancel ? true : null">
      <slot name="button-content"/>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { usePointerForwarding } from '../bridge/bridge'

defineOptions({ inheritAttrs: false })

const emit = defineEmits(['press', 'pressRelease', 'pressCancel'])

const props = defineProps({
  id: { type: String, required: true },
  action: String,
  press: { type: Boolean, default: false },
  reactPress: { type: Boolean, default: false },
  reactPressRelease: { type: Boolean, default: false },
  reactPressCancel: { type: Boolean, default: false }
})

const buttonEl = ref(null)
const buttonItem = ref(null)

usePointerForwarding({
  elRef: buttonItem,
  onReaction(e) {
    const event = e.detail?.event
    if (!event) return

    if (event === 'press' && !props.reactPress) return
    if (event === 'pressRelease' && !props.reactPressRelease) return
    if (event === 'pressCancel' && !props.reactPressCancel) return

    if (event === 'press') emit('press', e.detail)
    if (event === 'pressRelease') emit('pressRelease', e.detail)
    if (event === 'pressCancel') emit('pressCancel', e.detail)
  }
})
</script>

<style scoped>
.non-interactive-default {
  position: relative;
  pointer-events: none;
}

.interactive-default {
  position: absolute;
  user-select: none;
  pointer-events: auto;
}
</style>

// web-react/src/components/primitives/button/Button.tsx
import { useRef } from "react"
import { usePointerForwarding } from "@interaction/bridge/bridge.ts"

export interface ButtonProps {
  id: string
  className?: string
  action?: string
  reactPress?: boolean
  reactPressRelease?: boolean
  reactPressCancel?: boolean
  interactive?: boolean
  onPress?: (detail: unknown) => void
  onPressRelease?: (detail: unknown) => void
  onPressCancel?: (detail: unknown) => void
  children?: React.ReactNode
  [key: string]: unknown
}

export default function Button({
  id,
  className,
  action,
  reactPress,
  reactPressRelease,
  reactPressCancel,
  interactive = true,
  onPress,
  onPressRelease,
  onPressCancel,
  children,
  ...rest
}: ButtonProps) {

  const buttonRef = useRef<HTMLDivElement>(null)

  usePointerForwarding({
    elRef: buttonRef,
    disabled: !interactive,
    onReaction: (reaction) => {
      const event = reaction.detail?.event
      if (!event) return

      if (event === 'press' && reactPress && onPress) {
        onPress(reaction.detail)
      }
      if (event === 'pressRelease' && reactPressRelease && onPressRelease) {
        onPressRelease(reaction.detail)
      }
      if (event === 'pressCancel' && reactPressCancel && onPressCancel) {
        onPressCancel(reaction.detail)
      }
    }
  })

  return (
    <div className="non-interactive-default">
      <div
        ref={buttonRef}
        className={`interactive-default ${className ?? ''}`}
        style={{ pointerEvents: interactive ? "auto" : "none" }}
        data-type="button"
        data-id={id}
        data-press={true}
        data-action={action || undefined}
        data-react-press={reactPress || undefined}
        data-react-press-release={reactPressRelease || undefined}
        data-react-press-cancel={reactPressCancel || undefined}
        {...rest}
      >
        {children}
      </div>
    </div>
  )
}
